In [57]:
from tensorflow.keras.datasets import imdb

In [58]:
word_index = imdb.get_word_index()
index_word = {v:k for k ,v in word_index.items()}

In [59]:
(X_, y_), (X_test, y_test) = imdb.load_data()

In [60]:
index_word.get(X_[0][0])

'the'

In [61]:
def imdb_comment(x):
    comment = ''
    for word in x:
        comment += index_word.get(word)+' '
    return comment

In [62]:
imdb_comment(X_[0])

"the as you with out themselves powerful lets loves their becomes reaching had journalist of lot from anyone to have after out atmosphere never more room titillate it so heart shows to years of every never going villaronga help moments or of every chest visual movie except her was several of enough more with is now current film as you of mine potentially unfortunately of you than him that with out themselves her get for was camp of you movie sometimes movie that with scary but pratfalls to story wonderful that in seeing in character to of 70s musicians with heart had shadows they of here that with her serious to have does when from why what have critics they is you that isn't one will very to as itself with other tricky in of seen over landed for anyone of gilmore's br show's to whether from than out themselves history he name half some br of 'n odd was two most of mean for 1 any an boat she he should is thought frog but of script you not while history he heart to real at barrel but wh

In [63]:
imdb_comment(X_[1])

"the thought solid thought senator do making to is spot nomination assumed while he of jack in where picked as getting on was did hands fact characters to always life thrillers not as me can't in at are br of sure your way of little it strongly random to view of love it so principles of guy it used producer of where it of here icon film of outside to don't all unique some like of direction it if out her imagination below keep of queen he diverse to makes this stretch stefan of solid it thought begins br senator machinations budget worthwhile though ok brokedown awaiting for ever better were lugia diverse for budget look kicked any to of making it out bosworth's follows for effects show to show cast this family us scenes more it severe making senator to levant's finds tv tend to of emerged these thing wants but fuher an beckinsale cult as it is video do you david see scenery it in few those are of ship for with of wild to one is very work dark they don't do dvd with those them "

In [218]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from collections import Counter
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization, Dropout

In [65]:
lengths = np.array([len(x) for x in X_])
np.mean(lengths), np.median(lengths), np.max(lengths)

(238.71364, 178.0, 2494)

In [66]:
word_set = []
for word in X_:
    word_set.extend(word)

In [67]:
word_cnt = Counter(word_set)
word_cnt.most_common

<bound method Counter.most_common of Counter({4: 336148, 5: 164097, 6: 163040, 7: 145847, 8: 135708, 9: 107313, 10: 101871, 11: 93934, 12: 79058, 13: 77142, 14: 75974, 15: 69787, 16: 48195, 17: 46927, 18: 44335, 19: 44122, 20: 43564, 21: 42594, 22: 39095, 23: 34188, 24: 30610, 25: 29877, 26: 29425, 27: 29366, 28: 27726, 29: 26952, 30: 26948, 31: 26513, 1: 25000, 32: 23953, 33: 23507, 34: 22539, 35: 21538, 36: 21139, 37: 20599, 38: 20586, 39: 20494, 40: 20272, 41: 18407, 42: 17994, 43: 17759, 44: 17371, 45: 17153, 46: 17092, 48: 16790, 47: 16790, 49: 15743, 50: 15735, 51: 15349, 52: 15100, 53: 14246, 54: 14175, 55: 14062, 56: 13274, 57: 12690, 58: 12682, 59: 12657, 60: 12650, 61: 12492, 62: 12238, 63: 12041, 64: 11915, 65: 11892, 66: 11734, 67: 11460, 68: 11376, 69: 11287, 70: 11120, 71: 10783, 72: 10742, 73: 10644, 74: 9919, 75: 9866, 76: 9758, 77: 9287, 78: 9270, 79: 9269, 80: 9193, 81: 9161, 82: 9157, 83: 9110, 84: 9102, 85: 9079, 86: 9057, 87: 9045, 88: 9044, 89: 8870, 90: 8865, 91:

In [68]:
words = [words for words, _ in word_cnt.most_common(1000)]

In [69]:
X_1 = []
for idx, word in enumerate(X_[0]):
    if word not in words:
        X_[0][idx] = 0


In [70]:
def common_word(x):
    for idx, word in enumerate(x):
        if word not in words:
            x[idx] = 0
    return x

In [71]:
X_ = pd.Series(X_).apply(common_word, 1)

In [72]:
X_

0        [1, 14, 22, 16, 43, 530, 973, 0, 0, 65, 458, 0...
1        [1, 194, 0, 194, 0, 78, 228, 5, 6, 0, 0, 0, 13...
2        [1, 14, 47, 8, 30, 31, 7, 4, 249, 108, 7, 4, 0...
3        [1, 4, 0, 0, 33, 0, 4, 0, 432, 111, 153, 103, ...
4        [1, 249, 0, 7, 61, 113, 10, 10, 13, 0, 14, 20,...
                               ...                        
24995    [1, 14, 9, 6, 0, 20, 21, 0, 7, 0, 5, 0, 86, 58...
24996    [1, 0, 0, 299, 6, 0, 37, 80, 81, 233, 8, 401, ...
24997    [1, 11, 6, 230, 245, 0, 9, 6, 0, 446, 0, 45, 0...
24998    [1, 0, 0, 69, 72, 0, 13, 610, 930, 8, 12, 582,...
24999    [1, 17, 6, 194, 337, 7, 4, 204, 22, 45, 254, 8...
Length: 25000, dtype: object

In [73]:
np.array(X_[0])[np.array(X_[0]) > 0]

array([  1,  14,  22,  16,  43, 530, 973,  65, 458,  66,   4, 173,  36,
       256,   5,  25, 100,  43, 838, 112,  50, 670,   9,  35, 480, 284,
         5, 150,   4, 172, 112, 167, 336, 385,  39,   4, 172,  17, 546,
        38,  13, 447,   4, 192,  50,  16,   6, 147,  19,  14,  22,   4,
       469,   4,  22,  71,  87,  12,  16,  43, 530,  38,  76,  15,  13,
         4,  22,  17, 515,  17,  12,  16, 626,  18,   5,  62, 386,  12,
         8, 316,   8, 106,   5,   4,  16, 480,  66,  33,   4, 130,  12,
        16,  38, 619,   5,  25, 124,  51,  36, 135,  48,  25,  33,   6,
        22,  12, 215,  28,  77,  52,   5,  14, 407,  16,  82,   8,   4,
       107, 117,  15, 256,   4,   7,   5, 723,  36,  71,  43, 530, 476,
        26, 400, 317,  46,   7,   4,  13, 104,  88,   4, 381,  15, 297,
        98,  32,  56,  26, 141,   6, 194,  18,   4, 226,  22,  21, 134,
       476,  26, 480,   5, 144,  30,  18,  51,  36,  28, 224,  92,  25,
       104,   4, 226,  65,  16,  38,  88,  12,  16, 283,   5,  1

In [74]:
np.array(X_[0])[np.array(X_[0]) > 0].size

189

In [75]:
def remove_zero(x):
    return np.array(x)[np.array(x) > 0]

In [76]:
X_ = pd.Series(X_).apply(common_word, 1).apply(remove_zero, 1)

In [77]:
X_.apply(len).mean()

182.51284

In [78]:
np.ceil(X_.apply(len).mean()).astype(int)

183

In [79]:
def comment_slice(x):
    if len(x) < 183:
        tmp = [0]*(183-len(x))
        x = np.append(x, tmp)
    return x[:183]

In [80]:
X_ = pd.Series(X_).apply(comment_slice, 1)

In [81]:
X_.apply(len)

0        183
1        183
2        183
3        183
4        183
        ... 
24995    183
24996    183
24997    183
24998    183
24999    183
Length: 25000, dtype: int64

In [82]:
X_test = pd.Series(X_test).apply(common_word, 1).apply(remove_zero, 1).apply(comment_slice, 1)

In [83]:
X_train, X_validation, y_train, y_validation = train_test_split(X_, y_)

In [84]:
y_train

array([0, 1, 0, ..., 1, 1, 1], dtype=int64)

In [86]:
X_train[0]

array([  1,  14,  22,  16,  43, 530, 973,  65, 458,  66,   4, 173,  36,
       256,   5,  25, 100,  43, 838, 112,  50, 670,   9,  35, 480, 284,
         5, 150,   4, 172, 112, 167, 336, 385,  39,   4, 172,  17, 546,
        38,  13, 447,   4, 192,  50,  16,   6, 147,  19,  14,  22,   4,
       469,   4,  22,  71,  87,  12,  16,  43, 530,  38,  76,  15,  13,
         4,  22,  17, 515,  17,  12,  16, 626,  18,   5,  62, 386,  12,
         8, 316,   8, 106,   5,   4,  16, 480,  66,  33,   4, 130,  12,
        16,  38, 619,   5,  25, 124,  51,  36, 135,  48,  25,  33,   6,
        22,  12, 215,  28,  77,  52,   5,  14, 407,  16,  82,   8,   4,
       107, 117,  15, 256,   4,   7,   5, 723,  36,  71,  43, 530, 476,
        26, 400, 317,  46,   7,   4,  13, 104,  88,   4, 381,  15, 297,
        98,  32,  56,  26, 141,   6, 194,  18,   4, 226,  22,  21, 134,
       476,  26, 480,   5, 144,  30,  18,  51,  36,  28, 224,  92,  25,
       104,   4, 226,  65,  16,  38,  88,  12,  16, 283,   5,  1

In [87]:
X_train_trans = X_train.values[0].reshape(-1, 183)
for i in X_train.values[1:]:
    X_train_trans = np.append(X_train_trans, i.reshape(-1, 183), 0)

In [88]:
X_validation_trans = X_validation.values[0].reshape(-1, 183)
for i in X_validation.values[1:]:
    X_validation_trans = np.append(X_validation_trans, i.reshape(-1, 183), 0)

In [89]:
model = Sequential(
    [
        Dense(1024, activation='relu', input_shape=(183,)),
        BatchNormalization(),
        Dense(512, activation='relu'),
        BatchNormalization(),
        Dense(32, activation='relu'),
        BatchNormalization(),
        Dense(1, activation='sigmoid')
    ]
)

In [90]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics='accuracy')

In [92]:
model.fit(X_train_trans, y_train, epochs=20, validation_data=(X_validation_trans, y_validation))

Epoch 1/20
586/586 [==============================] - 3s 5ms/step - loss: 0.2383 - accuracy: 0.8995 - val_loss: 1.5807 - val_accuracy: 0.5109
Epoch 2/20
586/586 [==============================] - 3s 6ms/step - loss: 0.2231 - accuracy: 0.9095 - val_loss: 1.6675 - val_accuracy: 0.5026
Epoch 3/20
586/586 [==============================] - 3s 5ms/step - loss: 0.2044 - accuracy: 0.9170 - val_loss: 1.7052 - val_accuracy: 0.5027
Epoch 4/20
586/586 [==============================] - 3s 5ms/step - loss: 0.1851 - accuracy: 0.9260 - val_loss: 1.8227 - val_accuracy: 0.5032
Epoch 5/20
586/586 [==============================] - 3s 5ms/step - loss: 0.1707 - accuracy: 0.9338 - val_loss: 1.8642 - val_accuracy: 0.5040
Epoch 6/20
586/586 [==============================] - 3s 5ms/step - loss: 0.1662 - accuracy: 0.9353 - val_loss: 1.8912 - val_accuracy: 0.5216
Epoch 7/20
586/586 [==============================] - 3s 5ms/step - loss: 0.1565 - accuracy: 0.9379 - val_loss: 2.0366 - val_accuracy: 0.5109
Epoch 

In [93]:
X_train_trans[[0]]

array([[  1, 394,  13,  92, 181,   8,  30,  99,  21,  14,  22,  47,  35,
          7, 379,  51,   6,  13,  43, 426, 264,  89,  78,  14,  20,   9,
          4,  26,  43,  55, 680,   5, 125,   4, 370, 157,  33, 211,  43,
        527,   4, 228,  33, 211,  40,   6, 816,  18,   7,  13,  43, 296,
         14,  22,   8,  67,  89,  76, 433,  12,  70,  79,  49,   7,   4,
        499, 156,  26, 964, 806,  21,  32,  61,   5,   5, 233,  15,  70,
         23,  61, 648,   9,   8,   4,   9,   6,  87, 284,  21,  37, 694,
        279,  29,   9,  11,   8, 193,   6, 173,  11, 141,   6,  22,  14,
         20, 144,  28,  77,   8,  32,   4,  11,  32,   4,  22,  43,   8,
         98,   6,   7,  89,  24,   8,  97,   6,  22,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0

In [94]:
np.where(model.predict(X_train_trans[[0]]) > 0.5, 1, 0)

1/1 [==============================] - 0s 116ms/step


array([[0]])

In [101]:
y_train[0]

0

In [95]:
X_test[0]

array([  1, 591, 202,  14,  31,   6, 717,  10,  10,   5,   4, 360,   7,
         4, 177, 394, 354,   4, 123,   9,  10,  10,  13,  92, 124,  89,
       488, 100,  28,  14,  31,  23,  27,  29, 220, 468,   8, 124,  14,
       286, 170,   8, 157,  46,   5,  27, 239,  16, 179,  38,  32,  25,
       451, 202,  14,   6, 717,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [110]:
np.where(model.predict(X_test[5].reshape(1, -1)) > 0.5, 1, 0)

1/1 [==============================] - 0s 20ms/step


array([[0]])

In [111]:
y_test[5]

1

In [112]:
comment = '''That’s the feeling of many Iowa Republicans who are watching Donald Trump’s decisive victory tonight who were hoping the state would slow his steady march to the nomination.'''

In [123]:
word = []
for i in comment.split(' '):
    i = i.replace('.', '').replace(',','').replace('"','')
    if word_index.get(i) != None:
        word.append(word_index.get(i))
word = common_word(word)
word = remove_zero(word)
word = comment_slice(word)
word = word.reshape(1, -1)
    

In [124]:
word

array([[  1, 544,   4, 108,  34,  23, 146,  34,  68,   1,  59, 547,  24,
          5,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0

In [125]:
word.shape

(1, 183)

In [126]:
model.predict(word)[0][0]

1/1 [==============================] - 0s 19ms/step


1.0

In [130]:
def remove_words(x):
    return x.replace('.', '').replace(',','').replace('"','').replace('!','').replace("''",'').replace('?','')

In [151]:
def imdb_predict(model, comment):
    model = model
    word = []
    for i in comment.split(' '):
        i = remove_words(i)
        if word_index.get(i) != None:
            word.append(word_index.get(i))
    word = common_word(word)
    word = remove_zero(word)
    word = comment_slice(word)
    word = word.reshape(1, -1)
    return np.where(model.predict(word, verbose=0)[0] > 0.5, '긍정', '부정')[0]

In [152]:
imdb_predict(model, comment)

'긍정'

In [155]:
from tensorflow.keras.layers import Embedding, Flatten

In [ ]:
Embedding(
    input_dim, # 들어가는게 얼마야
    output_dim, # 나가는게 얼마야
    input_length=None # 입력 시퀀스의 길이
)

In [158]:
model1 = Sequential(
    [
    Embedding(1000, 8, input_length=183),
    Flatten(),
    Dense(128, activation='relu'),
    BatchNormalization(),
    Dense(64, activation='relu'),
    BatchNormalization(),
    Dense(32, activation='relu'),
    BatchNormalization(),
    Dense(1, activation='sigmoid')
    ]
)

In [160]:
model1.compile(optimizer='adam', loss='binary_crossentropy', metrics='accuracy')

In [171]:
x = np.random.randint(1, 1000, 183).reshape(1, -1)

In [172]:
model1.predict(x)

1/1 [==============================] - 0s 20ms/step


array([[0.5006222]], dtype=float32)

In [226]:
from collections import Counter
from tensorflow.keras.datasets import imdb
from tensorflow.keras.utils import pad_sequences, to_categorical
from tensorflow.keras.layers import Dropout

In [180]:
(X_, y_),(X_test, y_test) = imdb.load_data()
X = np.append(X_, X_test, 0)
y = np.append(y_, y_test)

In [181]:
word_index = imdb.get_word_index()

In [182]:
index_word = {v:k for k ,v in word_index.items()}

In [184]:
pad_sequences(X_test, 200).shape

(25000, 200)

In [185]:
for idx1, ind_word in enumerate(X):
    for idx2, val in enumerate(ind_word):
        X[idx1][idx2] = index_word.get(X[idx1][idx2])

In [186]:
X

array([list(['the', 'as', 'you', 'with', 'out', 'themselves', 'powerful', 'lets', 'loves', 'their', 'becomes', 'reaching', 'had', 'journalist', 'of', 'lot', 'from', 'anyone', 'to', 'have', 'after', 'out', 'atmosphere', 'never', 'more', 'room', 'titillate', 'it', 'so', 'heart', 'shows', 'to', 'years', 'of', 'every', 'never', 'going', 'villaronga', 'help', 'moments', 'or', 'of', 'every', 'chest', 'visual', 'movie', 'except', 'her', 'was', 'several', 'of', 'enough', 'more', 'with', 'is', 'now', 'current', 'film', 'as', 'you', 'of', 'mine', 'potentially', 'unfortunately', 'of', 'you', 'than', 'him', 'that', 'with', 'out', 'themselves', 'her', 'get', 'for', 'was', 'camp', 'of', 'you', 'movie', 'sometimes', 'movie', 'that', 'with', 'scary', 'but', 'pratfalls', 'to', 'story', 'wonderful', 'that', 'in', 'seeing', 'in', 'character', 'to', 'of', '70s', 'musicians', 'with', 'heart', 'had', 'shadows', 'they', 'of', 'here', 'that', 'with', 'her', 'serious', 'to', 'have', 'does', 'when', 'from', 'wh

In [187]:
word_list = []
for words in X:
    word_list.extend(words)

In [189]:
word_freq = Counter(word_list).most_common(1000)

In [191]:
word_to_index = { v:k for k, (v, _) in enumerate(word_freq, 1)}

In [193]:
index_to_word = {v: k for k, v in word_to_index.items()}

In [198]:
X

array([list(['the', 'as', 'you', 'with', 'out', 'themselves', 'powerful', 'lets', 'loves', 'their', 'becomes', 'reaching', 'had', 'journalist', 'of', 'lot', 'from', 'anyone', 'to', 'have', 'after', 'out', 'atmosphere', 'never', 'more', 'room', 'titillate', 'it', 'so', 'heart', 'shows', 'to', 'years', 'of', 'every', 'never', 'going', 'villaronga', 'help', 'moments', 'or', 'of', 'every', 'chest', 'visual', 'movie', 'except', 'her', 'was', 'several', 'of', 'enough', 'more', 'with', 'is', 'now', 'current', 'film', 'as', 'you', 'of', 'mine', 'potentially', 'unfortunately', 'of', 'you', 'than', 'him', 'that', 'with', 'out', 'themselves', 'her', 'get', 'for', 'was', 'camp', 'of', 'you', 'movie', 'sometimes', 'movie', 'that', 'with', 'scary', 'but', 'pratfalls', 'to', 'story', 'wonderful', 'that', 'in', 'seeing', 'in', 'character', 'to', 'of', '70s', 'musicians', 'with', 'heart', 'had', 'shadows', 'they', 'of', 'here', 'that', 'with', 'her', 'serious', 'to', 'have', 'does', 'when', 'from', 'wh

In [203]:
for idx1, ind_word in enumerate(X):
    for idx2, val in enumerate(ind_word):
        if word_to_index.get(X[idx1][idx2]) != None:
            X[idx1][idx2] = word_to_index.get(X[idx1][idx2])
        else:
            X[idx1][idx2] = 0

In [206]:
X = pd.Series(X).apply(lambda x: np.array(x)[np.array(x)>0]).values

In [207]:
X = pad_sequences(X, 200)

In [211]:
X_, X_test, y_, y_test = train_test_split(X, y)

In [212]:
X_train, X_validation, y_train, y_validation = train_test_split(X_, y_)

In [213]:
X_.shape, X_test.shape, X_train.shape, X_validation.shape

((37500, 200), (12500, 200), (28125, 200), (9375, 200))

In [214]:
y_train = y_train.reshape(-1, 1)
y_validation = y_validation.reshape(-1, 1)
y_test = y_test.reshape(-1, 1)

In [222]:
model_embedding = Sequential(
    [
    Embedding(1001, 8, input_length=200),
    Flatten(),
    Dense(256, activation='relu'),
    BatchNormalization(),
    Dense(128, activation='relu'),
    BatchNormalization(),
    Dense(64, activation='relu'),
    BatchNormalization(),
    Dense(32, activation='relu'),
    BatchNormalization(),
    Dense(1, activation='sigmoid')
    ]
)

In [223]:
model_embedding.compile(optimizer='adam', loss='binary_crossentropy', metrics='accuracy')

In [224]:
model_embedding.fit(X_train, y_train, epochs=30, validation_data=(X_validation, y_validation))

Epoch 1/30
879/879 [==============================] - 5s 4ms/step - loss: 0.5609 - accuracy: 0.6802 - val_loss: 0.3685 - val_accuracy: 0.8374
Epoch 2/30
879/879 [==============================] - 3s 4ms/step - loss: 0.3361 - accuracy: 0.8527 - val_loss: 0.3443 - val_accuracy: 0.8540
Epoch 3/30
879/879 [==============================] - 4s 4ms/step - loss: 0.2689 - accuracy: 0.8866 - val_loss: 0.3920 - val_accuracy: 0.8422
Epoch 4/30
879/879 [==============================] - 4s 4ms/step - loss: 0.2099 - accuracy: 0.9146 - val_loss: 0.4476 - val_accuracy: 0.8291
Epoch 5/30
879/879 [==============================] - 3s 4ms/step - loss: 0.1575 - accuracy: 0.9383 - val_loss: 0.4870 - val_accuracy: 0.8295
Epoch 6/30
879/879 [==============================] - 3s 4ms/step - loss: 0.1172 - accuracy: 0.9557 - val_loss: 0.5831 - val_accuracy: 0.8124
Epoch 7/30
879/879 [==============================] - 3s 4ms/step - loss: 0.0963 - accuracy: 0.9638 - val_loss: 0.6111 - val_accuracy: 0.8273
Epoch 

In [225]:
model_embedding.evaluate(X_test, y_test)

391/391 [==============================] - 1s 1ms/step - loss: 1.0727 - accuracy: 0.8199


[1.072727918624878, 0.819920003414154]

In [228]:
from keras.datasets import reuters 

In [229]:
(X_, y_),(X_test, y_test) = reuters.load_data()
X = np.append(X_, X_test, 0)
y = np.append(y_, y_test)
word_index = imdb.get_word_index()
index_word = {v:k for k ,v in word_index.items()}
pad_sequences(X_test, 200).shape
for idx1, ind_word in enumerate(X):
    for idx2, val in enumerate(ind_word):
        X[idx1][idx2] = index_word.get(X[idx1][idx2])
word_list = []
for words in X:
    word_list.extend(words)
word_freq = Counter(word_list).most_common(1000)
word_to_index = { v:k for k, (v, _) in enumerate(word_freq, 1)}
index_to_word = {v: k for k, v in word_to_index.items()}
for idx1, ind_word in enumerate(X):
    for idx2, val in enumerate(ind_word):
        if word_to_index.get(X[idx1][idx2]) != None:
            X[idx1][idx2] = word_to_index.get(X[idx1][idx2])
        else:
            X[idx1][idx2] = 0
X = pd.Series(X).apply(lambda x: np.array(x)[np.array(x)>0]).values
X = pad_sequences(X, 200)
y = to_categorical(y)
X_, X_test, y_, y_test = train_test_split(X, y)
X_train, X_validation, y_train, y_validation = train_test_split(X_, y_)

2110848/2110848 [==============================] - 0s 0us/step


In [230]:
model_reuter = Sequential(
    [
    Embedding(1001, 8, input_length=200),
    Flatten(),
    Dense(256, activation='relu'),
    BatchNormalization(),
    Dense(128, activation='relu'),
    BatchNormalization(),
    Dense(64, activation='relu'),
    BatchNormalization(),
    Dense(46, activation='softmax')
    ]
)

In [235]:
model_reuter.compile(optimizer='adam', loss='categorical_crossentropy', metrics='accuracy')

In [237]:
model_reuter.fit(X_train, y_train, epochs=30, validation_data=(X_validation, y_validation))

Epoch 1/30
198/198 [==============================] - 1s 5ms/step - loss: 0.1085 - accuracy: 0.9633 - val_loss: 2.4497 - val_accuracy: 0.6144
Epoch 2/30
198/198 [==============================] - 1s 4ms/step - loss: 0.1049 - accuracy: 0.9644 - val_loss: 2.4269 - val_accuracy: 0.6154
Epoch 3/30
198/198 [==============================] - 1s 4ms/step - loss: 0.1148 - accuracy: 0.9633 - val_loss: 2.4785 - val_accuracy: 0.6187
Epoch 4/30
198/198 [==============================] - 1s 4ms/step - loss: 0.1166 - accuracy: 0.9606 - val_loss: 2.5140 - val_accuracy: 0.6092
Epoch 5/30
198/198 [==============================] - 1s 4ms/step - loss: 0.1132 - accuracy: 0.9617 - val_loss: 2.5162 - val_accuracy: 0.6154
Epoch 6/30
198/198 [==============================] - 1s 4ms/step - loss: 0.1451 - accuracy: 0.9525 - val_loss: 2.5558 - val_accuracy: 0.6049
Epoch 7/30
198/198 [==============================] - 1s 4ms/step - loss: 0.1311 - accuracy: 0.9558 - val_loss: 2.6397 - val_accuracy: 0.6154
Epoch 

In [238]:
from tensorflow.keras.layers import Conv1D, MaxPooling1D

In [239]:
model_reuter = Sequential(
    [
    Embedding(1001, 8, input_length=200),
    Conv1D(20, 7, activation='relu'),
    MaxPooling1D(2),
    Flatten(),
    Dense(256, activation='relu'),
    BatchNormalization(),
    Dense(128, activation='relu'),
    BatchNormalization(),
    Dense(64, activation='relu'),
    BatchNormalization(),
    Dense(46, activation='softmax')
    ]
)

In [240]:
model_reuter.compile(optimizer='adam', loss='categorical_crossentropy', metrics='accuracy')

In [241]:
model_reuter.fit(X_train, y_train, epochs=30, validation_data=(X_validation, y_validation))

Epoch 1/30
198/198 [==============================] - 3s 6ms/step - loss: 2.4573 - accuracy: 0.4763 - val_loss: 2.3835 - val_accuracy: 0.3908
Epoch 2/30
198/198 [==============================] - 1s 6ms/step - loss: 1.5162 - accuracy: 0.6473 - val_loss: 1.9519 - val_accuracy: 0.5000
Epoch 3/30
198/198 [==============================] - 1s 5ms/step - loss: 1.1358 - accuracy: 0.7276 - val_loss: 1.6836 - val_accuracy: 0.6268
Epoch 4/30
198/198 [==============================] - 1s 5ms/step - loss: 0.8510 - accuracy: 0.7884 - val_loss: 1.7152 - val_accuracy: 0.6287
Epoch 5/30
198/198 [==============================] - 1s 5ms/step - loss: 0.6237 - accuracy: 0.8467 - val_loss: 1.9662 - val_accuracy: 0.6230
Epoch 6/30
198/198 [==============================] - 1s 5ms/step - loss: 0.4802 - accuracy: 0.8841 - val_loss: 1.9517 - val_accuracy: 0.6339
Epoch 7/30
198/198 [==============================] - 1s 6ms/step - loss: 0.3452 - accuracy: 0.9184 - val_loss: 2.0230 - val_accuracy: 0.6287
Epoch 

In [242]:
model_reuter.evaluate(X_test, y_test)

88/88 [==============================] - 0s 2ms/step - loss: 2.5793 - accuracy: 0.6377


[2.5792973041534424, 0.6376914978027344]

In [12]:
import konlpy
import pandas as pd

In [13]:
data = pd.read_csv("kedi.csv", encoding='cp949')

In [14]:
data.head()

프로그램명 대계열코드   대계열  중분류코드  중분류     소분류코드  소분류  \
0                 10명중9명이틀리는한글맞춤법   L01  인문계열  L0101  한국어  L0101001  한국어   
1                 10명중9명이틀리는한글맞춤법   L01  인문계열  L0101  한국어  L0101001  한국어   
2       10명중9명이틀리는한글맞춤법(참고도서전집제공)   L01  인문계열  L0101  한국어  L0101001  한국어   
3  10명중9명이틀리는한글맞춤법(참고도서제공)[스마트러닝]   L01  인문계열  L0101  한국어  L0101001  한국어   
4          10명중9명이틀리는한글맞춤법[스마트러닝]   L01  인문계열  L0101  한국어  L0101001  한국어   

   프로그램수   학생수  
0      1    56  
1      2    32  
2      2     4  
3      1  3472  
4      1     1

In [4]:
pip install konlpy

In [5]:
from konlpy.tag import Kkma, Komoran, Okt, Twitter
import konlpy.tag

In [7]:
okt = Okt()
kkma = Kkma()

In [8]:
sentence = "아버지가방에들어가신다"

In [9]:
kkma.pos(sentence)

[('아버지', 'NNG'),
 ('가방', 'NNG'),
 ('에', 'JKM'),
 ('들어가', 'VV'),
 ('시', 'EPH'),
 ('ㄴ다', 'EFN')]

In [10]:
kkma.nouns(sentence)

['아버지', '아버지가방', '가방']

In [11]:
okt.nouns(sentence)

['아버지', '가방']

In [15]:
X = data['프로그램명']

In [16]:
y = data['소분류']

In [17]:
X = X.apply(okt.nouns)

In [18]:
words = []
for word in X:
    words.extend(word)

In [19]:
words_list = list(set(words))

In [20]:
word_to_index = {v:k for k,v in enumerate(words_list)}
index_to_word = {v:k for k,v in word_to_index.items()}

In [22]:
word_to_index.get('명중')

6667

In [23]:
def make_index(x):
    for idx, word in enumerate(x):
        x[idx] = word_to_index.get(word)
    return x

In [24]:
X = X.apply(make_index)

In [25]:
X

0                              [6667, 3149, 11022]
1                              [6667, 3149, 11022]
2           [6667, 3149, 11022, 5784, 10947, 2206]
3            [6667, 3149, 11022, 5784, 2206, 9365]
4                        [6667, 3149, 11022, 9365]
                            ...                   
125165    [9931, 12186, 14517, 2305, 15118, 12385]
125166                         [6613, 16637, 2554]
125167                 [6613, 12015, 12186, 16637]
125168                               [3886, 16637]
125169                         [3886, 16637, 2554]
Name: 프로그램명, Length: 125170, dtype: object

In [26]:
X = X[1:]
y = y[1:]

In [28]:
import numpy as np

In [29]:
np.unique(y.values)

array(['OA', '간호', '건강·미용', '건설·건축·토목', '게임', '결혼·가족·가정', '경영이론', '경영정보',
       '경제', '과학이론·교양', '과학일반', '관광·호텔', '교육학', '교통·운송', '국사', '국악·민요',
       '그림·회화', '글씨디자인', '금융재무', '기계·금속', '기타외국어', '꽃예술', '논술·구술',
       '논술·글쓰기', '농업·원예', '다도', '대중음악', '데이터베이스', '독서', '동·서양문학',
       '디자인이론·교양', '레저·스포츠', '레크리에이션', '마술', '마케팅', '멀티미디어', '무용이론·교양',
       '문학이론·문예창작', '문화', '미술', '미술이론·교양', '법학', '보건', '부동산', '사진·만화',
       '사회복지', '사회일반', '사회학', '생물·화학·물리·천문', '생산관리', '생활공예', '생활무용',
       '생활요리', '서양악기', '서예·서화', '성악', '소방·경찰·경호', '수학', '수화(손언어)', '식생활',
       '신문·방송·출판', '실내인테리어', '심리·상담', '아동발달', '아동지도', '언어', '여성', '역사',
       '연극', '영상예술', '영어', '운영체제', '윤리', '음악', '음악이론·교양', '응용치료', '의료',
       '의상디자인', '인문교양', '인터넷', '일러스트레이션', '일반 기타', '일본어', '입시 기타',
       '재료·정밀', '전기·전자', '전략·국제경영', '전통공예', '전통무용', '전통악기', '정치', '정치학',
       '제2외국어', '제과제빵', '조직관리', '조형', '종교', '종교음악', '중국어', '진로교육', '철학',
       '체육이론·교양', '취업·창업', '컴퓨터기초', '통계', '통신', '풍수·사주', '프로그래밍', '한국문학',
    

In [38]:
index_to_subject = dict(zip(np.arange(np.unique(y.values).size), np.unique(y.values)))

In [39]:
subject_to_index = {v:k for k,v in index_to_subject.items()}

In [43]:
subject_to_index

{'OA': 0,
 '간호': 1,
 '건강·미용': 2,
 '건설·건축·토목': 3,
 '게임': 4,
 '결혼·가족·가정': 5,
 '경영이론': 6,
 '경영정보': 7,
 '경제': 8,
 '과학이론·교양': 9,
 '과학일반': 10,
 '관광·호텔': 11,
 '교육학': 12,
 '교통·운송': 13,
 '국사': 14,
 '국악·민요': 15,
 '그림·회화': 16,
 '글씨디자인': 17,
 '금융재무': 18,
 '기계·금속': 19,
 '기타외국어': 20,
 '꽃예술': 21,
 '논술·구술': 22,
 '논술·글쓰기': 23,
 '농업·원예': 24,
 '다도': 25,
 '대중음악': 26,
 '데이터베이스': 27,
 '독서': 28,
 '동·서양문학': 29,
 '디자인이론·교양': 30,
 '레저·스포츠': 31,
 '레크리에이션': 32,
 '마술': 33,
 '마케팅': 34,
 '멀티미디어': 35,
 '무용이론·교양': 36,
 '문학이론·문예창작': 37,
 '문화': 38,
 '미술': 39,
 '미술이론·교양': 40,
 '법학': 41,
 '보건': 42,
 '부동산': 43,
 '사진·만화': 44,
 '사회복지': 45,
 '사회일반': 46,
 '사회학': 47,
 '생물·화학·물리·천문': 48,
 '생산관리': 49,
 '생활공예': 50,
 '생활무용': 51,
 '생활요리': 52,
 '서양악기': 53,
 '서예·서화': 54,
 '성악': 55,
 '소방·경찰·경호': 56,
 '수학': 57,
 '수화(손언어)': 58,
 '식생활': 59,
 '신문·방송·출판': 60,
 '실내인테리어': 61,
 '심리·상담': 62,
 '아동발달': 63,
 '아동지도': 64,
 '언어': 65,
 '여성': 66,
 '역사': 67,
 '연극': 68,
 '영상예술': 69,
 '영어': 70,
 '운영체제': 71,
 '윤리': 72,
 '음악': 73,
 '음악이론·교양': 74,
 '응용치료': 7

In [40]:
def make_subject_index(x):
    x = subject_to_index.get(x)
    return x

In [44]:
y = y.apply(make_subject_index)

In [54]:
from tensorflow.keras.utils import to_categorical, pad_sequences

In [47]:
y = to_categorical(y)

In [49]:
y.shape

(125169, 117)

In [51]:
X.apply(len).max()

21

In [55]:
X = pad_sequences(X, maxlen=21)

In [59]:
from tensorflow.keras.layers import Dense, Conv1D, MaxPooling1D, BatchNormalization, Embedding, Flatten
from tensorflow.keras.models import Sequential

In [60]:
max(index_to_word.keys())

16704

In [62]:
y.shape

(125169, 117)

In [63]:
model = Sequential(
    [
        Embedding(16705, 8, input_length=21),
        Conv1D(10, 2, activation='relu'),
        MaxPooling1D(2),
        Flatten(),
        Dense(256, activation='relu'),
        BatchNormalization(),
        Dense(117, activation='softmax')
    ]
)

In [64]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics='accuracy')

In [65]:
model.fit(X, y, epochs=10)

Epoch 1/10


3912/3912 [==============================] - 11s 2ms/step - loss: 1.7517 - accuracy: 0.5942
Epoch 2/10
3912/3912 [==============================] - 8s 2ms/step - loss: 1.0632 - accuracy: 0.7405
Epoch 3/10
3912/3912 [==============================] - 8s 2ms/step - loss: 0.9043 - accuracy: 0.7742
Epoch 4/10
3912/3912 [==============================] - 8s 2ms/step - loss: 0.8220 - accuracy: 0.7934
Epoch 5/10
3912/3912 [==============================] - 8s 2ms/step - loss: 0.7626 - accuracy: 0.8054
Epoch 6/10
3912/3912 [==============================] - 8s 2ms/step - loss: 0.7276 - accuracy: 0.8122
Epoch 7/10
3912/3912 [==============================] - 8s 2ms/step - loss: 0.6985 - accuracy: 0.8186
Epoch 8/10
3912/3912 [==============================] - 8s 2ms/step - loss: 0.6723 - accuracy: 0.8246
Epoch 9/10
3912/3912 [==============================] - 8s 2ms/step - loss: 0.6508 - accuracy: 0.8283
Epoch 10/10
3912/3912 [==============================] - 8s 2ms/step - loss: 0.

In [108]:
subject = "임태환선생님의요리"
def make_subject_index(subject):
    subject = okt.nouns(subject)
    subject_list = []
    for i in subject:
        subject_list.append(word_to_index.get(i, 0))
    return pad_sequences(np.array([subject_list]), 21)

In [109]:
result = model.predict(make_subject_index(subject))
result = np.argmax(result)

1/1 [==============================] - 0s 17ms/step


In [110]:
index_to_subject.get(result)

'생활요리'