In [1]:
pip install scikit-learn

In [41]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [42]:
x = np.random.randint(1, 100, 50)


In [43]:
a = np.random.choice(np.arange(100), 1)
y = a * x + np.random.randn(50)

In [44]:
a

array([52])

In [45]:
pd.DataFrame(x, y)

0
157.597549    3
4213.965181  81
3537.001553  68
676.598420   13
1768.273480  34
2806.569066  54
779.124210   15
1505.428954  29
2081.240944  40
1352.163279  26
2131.317421  41
1818.842950  35
1302.258839  25
2029.197514  39
625.099355   12
5043.689900  97
311.706490    6
4681.022296  90
3067.847896  59
2287.250817  44
2183.746013  42
832.956490   16
2288.058217  44
572.448317   11
2910.809417  56
5148.070981  99
2704.917817  52
1923.720102  37
3586.805709  69
4316.961770  83
3171.349217  61
2497.469033  48
2182.917279  42
831.836367   16
5093.602346  98
1612.952214  31
1508.475072  29
1196.201270  23
4629.098600  89
2029.139392  39
2757.207040  53
1250.397848  24
153.328590    3
4939.375097  95
104.116870    2
2808.332254  54
1456.086375  28
2288.036879  44
3951.057658  76
156.287284    3

In [46]:
a_hat = np.random.randn(1)

In [47]:
a_hat

array([-1.6360076])

In [48]:
y_hat = a_hat * x

In [49]:
y_hat

array([  -4.9080228 , -132.51661563, -111.24851683,  -21.26809881,
        -55.62425841,  -88.34441042,  -24.54011401,  -47.44422041,
        -65.44030402,  -42.53619761,  -67.07631162,  -57.26026601,
        -40.90019001,  -63.80429642,  -19.6320912 , -158.69273724,
         -9.8160456 , -147.24068404,  -96.52444842,  -71.98433442,
        -68.71231922,  -26.17612161,  -71.98433442,  -17.9960836 ,
        -91.61642562, -161.96475244,  -85.07239522,  -60.53228121,
       -112.88452443, -135.78863083,  -99.79646362,  -78.52836482,
        -68.71231922,  -26.17612161, -160.32874484,  -50.71623561,
        -47.44422041,  -37.62817481, -145.60467644,  -63.80429642,
        -86.70840282,  -39.26418241,   -4.9080228 , -155.42072204,
         -3.2720152 ,  -88.34441042,  -45.80821281,  -71.98433442,
       -124.33657763,   -4.9080228 ])

In [50]:

np.sum((y_hat - y)**2)/y_hat.size

7649068.25833006

In [51]:
learning_rate = 1e-3
a_hat = a_hat - learning_rate*2*np.mean(x*(y_hat-y))

In [52]:
a_hat

array([283.57993352])

In [56]:
y_hat = a_hat*x
a_hat = a_hat - learning_rate*2*np.mean(x*(y_hat-y))
a_hat

array([80522.45533361])

In [58]:
def gradient_descent(x, y, learning_rate, epochs):
    a_hat = np.random.randn(1)
    for _ in range(epochs):
        y_hat = a_hat*x
        a_hat -= learning_rate*np.mean(x*(y_hat - y))
    return a_hat

In [59]:
x = np.random.randn(100)
y = 48*x

In [60]:
gradient_descent(x, y, 1e-4, 100000)

array([47.99706439])

In [84]:
X = np.random.randn(50)

In [85]:
y = -200 * X + 90

In [86]:
def gradient_descent(x, y, learning_rate, epochs):
    a_hat = 1000
    b_hat = 0
    for _ in range(epochs):
        y_hat = a_hat*x + b_hat
        a_hat -= learning_rate*np.mean(2*x*(y_hat-y))
        b_hat -= learning_rate*np.mean(2*(y_hat-y))
    return a_hat, b_hat

In [87]:
gradient_descent(x, y, 1e-4, 100000)

(-73.15020430678338, 82.17517364673711)

In [121]:
def diff(f, x):
    h = 1e-5
    return (f(x+h) - f(x))/h

In [122]:
np.array([1, 2])[0]

1

In [123]:
def fx(x):
    a = x[0]
    b = x[1]
    return np.mean(a*X + b)


def gradient_descent(x, y, learning_rate, epochs):
    a_hat = 1000
    for _ in range(epochs):
        fx = lambda W: np.mean(x*W)
        a_hat -= diff(fx, a_hat)*learning_rate
        
    return a_hat

X = np.random.randn(100)
y = 100*X

In [124]:
a_hat= gradient_descent(X, y, 1e-3, 1000)

In [125]:
a_hat1 = gradient_descent(X, y, 1e-3, 10000)

In [126]:
a_hat, a_hat1

(999.9221397644628, 999.2213976451781)

In [127]:
a_hat2 = gradient_descent(X, y, 1e-3, 100000)

In [128]:
a_hat2

992.2139764522835

In [129]:
a_hat = 1000
fx = lambda W: np.mean(X*W)
diff(fx, a_hat)

0.07786023559219757

In [130]:
np.mean(X*(1000+1e-5) - X*(1000))/(1e-5)

0.07786023565259369

In [141]:
def gradient_descent(x, y, learning_rate, epochs):
    a_hat = np.random.randn(1)
    b_hat = 0
    W = np.array([a_hat, b_hat])
    for _ in range(epochs):
        predict = lambda W : x*W[0] + W[1]
        loss = lambda y, predict : np.mean((y - predict)**2)
        W[0] -= diff(loss, W)[0]*learning_rate
        W[1] -= diff(loss, W)[1]*learning_rate


    return W[0], W[1]

In [142]:
X = np.random.rand(100)
y = x*100 + 20

In [143]:
gradient_descent(X, y, 1e-3, 10000)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.